packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - sharp
  - simple-git-hooks

overrides:
  '@types/react': 19.2.9
  '@types/react-dom': 19.2.3
  array-includes: npm:@nolyfill/array-includes@^1.0.44
  array.prototype.findlastindex: npm:@nolyfill/array.prototype.findlastindex@^1.0.44
  array.prototype.flat: npm:@nolyfill/array.prototype.flat@^1.0.44
  array.prototype.flatmap: npm:@nolyfill/array.prototype.flatmap@^1.0.44
  array.prototype.tosorted: npm:@nolyfill/array.prototype.tosorted@^1.0.44
  has: npm:@nolyfill/has@^1.0.44
  is-core-module: npm:@nolyfill/is-core-module@^1.0.39
  object.assign: npm:@nolyfill/object.assign@^1.0.44
  object.entries: npm:@nolyfill/object.entries@^1.0.44
  object.fromentries: npm:@nolyfill/object.fromentries@^1.0.44
  object.groupby: npm:@nolyfill/object.groupby@^1.0.44
  object.hasown: npm:@nolyfill/object.hasown@^1.0.44
  object.values: npm:@nolyfill/object.values@^1.0.44
  string.prototype.matchall: npm:@nolyfill/string.prototype.matchall@^1.0.44

patchedDependencies:
  '@haklex/rich-editor@0.0.105': patches/@haklex__rich-editor@0.0.105.patch
  '@innei/markdown-to-jsx-yet': patches/@innei__markdown-to-jsx-yet.patch
  next@16.1.6: patches/next@16.1.6.patch
